services:
  blog:
    # build: .
    image: volla12345/blogg:postgres
    ports:
      - "80:80"
    env_file:
      - app/.env
    depends_on:
      - db
    volumes:
      - rails_storage:/rails/storage

  db:
    image: postgres:16
    env_file:
      - app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rails_storage:
  postgres_data:
