user rails;

events {}

http {
    include /opt/nginx/conf/mime.types;
    default_type application/octet-stream;
    
    passenger_root /usr/local/bundle/ruby/3.4.0/gems/passenger-6.1.5;
    passenger_ruby /usr/local/bin/ruby;

    server {
        listen 80;

        root /rails/public;

        passenger_enabled on;
        passenger_app_env production;
    }
}